### ISSUE TITLE
error Invalid version: "https://registry.npmjs.org/hexo-util/-/hexo-util-0.6.0.tgz"

### ISSUE THREAD

**Issue by paul-hammant** [hexojs/hexo-util#26]
On previously working Hexo install, I do `rm -rf node_modules/ && npm install` and I get:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.3/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:highlight' ]
2 info using npm@5.0.3
3 info using node@v8.1.3
4 verbose stack Error: Invalid version: "https://registry.npmjs.org/hexo-util/-/hexo-util-0.6.0.tgz"
4 verbose stack     at Object.fixVersionField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:191:13)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
4 verbose stack     at Array.forEach (native)
4 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:243:12
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:512:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:500:12)
5 verbose cwd /scm/devops/node_modules/hexo-util
6 verbose Darwin 16.6.0
7 verbose argv "/usr/local/Cellar/node/8.1.3/bin/node" "/usr/local/bin/npm" "run" "build:highlight"
8 verbose node v8.1.3
9 verbose npm  v5.0.3
10 error Invalid version: "https://registry.npmjs.org/hexo-util/-/hexo-util-0.6.0.tgz"
11 verbose exit [ 1, true ]
```

Yeah, I've no idea what is invalid about the version number.

I'm on a Mac, with homebrew.

**Comment by paul-hammant** [comment]
Hmm - seems to be OK if I upgrade to node v8.1.4 and npm v5.0.3.
