### ISSUE TITLE
ERROR Plugin load failed: hexo-generator-json-content

### ISSUE THREAD

**Issue by VampireAchao** [hexojs/hexo-util#292]
```shell
PS D:\file\blog\blog> hexo clean
INFO  Validating config
ERROR Plugin load failed: hexo-generator-json-content
Error: Cannot find module 'D:\file\blog\blog\node_modules\hexo-generator-json-content\node_modules\hexo-util\lib\index'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:680:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at req (D:\file\blog\blog\node_modules\hexo\lib\hexo\index.js:292:23)
    at D:\file\blog\blog\node_modules\hexo-generator-json-content\dist\main.js:7:16
    at D:\file\blog\blog\node_modules\hexo\lib\hexo\index.js:305:14
    at tryCatcher (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\file\blog\blog\node_modules\hexo-fs\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
```

![image](https://user-images.githubusercontent.com/52746628/201833814-9adb1fb5-8fb1-45ce-931d-5027c9b83887.png)

**Comment by VampireAchao** [comment]
just enter the hexo-generator-json-content directory and cnpm install hexo-util@2.7

```shell
cd D:\file\blog\blog\node_modules\hexo-generator-json-content
# 安装 2.7版本
cnpm i hexo-util@2.7
```
and everything is normal,enjoy bloging~

![image](https://user-images.githubusercontent.com/52746628/201835760-a41b4568-b64f-4c1d-a9bb-ae92020a34c6.png)

☕

**Comment by VampireAchao** [comment]
sorry I publish a wrong place
