### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by dimaslanjaka** [hexojs/hexo-util#322]
just run `hexo generate` in my hexo site with more than 1.7k posts

```log
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at escapeRegExp (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo/node_modules/hexo-util/lib/escape_regexp.js:7:14)
    at slugize (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo/node_modules/hexo-util/lib/slugize.js:13:22)
    at _Document.<anonymous> (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo/lib/models/tag.js:21:12)
    at _Document.slug (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo/node_modules/warehouse/lib/types/virtual.js:59:24)
    at JSON.stringify (<anonymous>)
    at JSON.stringifyWithCircularRefs (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/sbg-utility/dist/utils/JSON.js:56:25)
    at jsonStringifyWithCircularRefs (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/sbg-utility/dist/utils/JSON.js:69:17)
    at /home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo-renderers/dist/helper/collector.js:161:122
    at step (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo-renderers/dist/helper/collector.js:56:23)
    at Object.next (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo-renderers/dist/helper/collector.js:37:53)
    at fulfilled (/home/runner/work/static-blog-generator-hexo/static-blog-generator-hexo/site/node_modules/hexo-renderers/dist/helper/collector.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Process completed with exit code 2.
```

**Comment by dimaslanjaka** [comment]
unrelated sorry
